// TODO: models should be autogenerated from c# classes
export module Status {
    export interface StatusDetails {
        Name: string
        Description: string
        Database: string
        Version: string
    }
}
